name: CI

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Release workflow
    timeout-minutes: 30
    runs-on: [self-hosted]
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.CI_ACCESS }}

      - name: Install Dependencies && test
        run: npm install && npm test

      - name: Install Semantic-Release
        shell: bash
        run: npm i -D semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/release-notes-generator

      - name: Semantic Release
        uses: codfish/semantic-release-action@v2
        id: semantic
        with:
          branches: |
            [
            'main'
            ]
          plugins: |
            [
              ['@semantic-release/commit-analyzer',{
                  'preset': 'angular',
                  'releaseRules': [
                    {
                      'type': 'docs',
                      'release': 'patch'
                    },
                    {
                      'type': 'refactor',
                      'release': 'patch'
                    },
                    {
                      'type': 'style',
                      'release': 'patch'
                    },
                    {
                      'type': 'chore',
                      'release': 'patch'
                    }
                  ]
                }
              ],
              '@semantic-release/release-notes-generator',
              ['@semantic-release/changelog', {'changelogFile': 'CHANGELOG.md','changelogTitle': '# Changelog'}],
              '@semantic-release/npm',
              ['@semantic-release/github',  {'successComment': false}],
              ['@semantic-release/git', {'assets': ['CHANGELOG.md', 'package.json']}]
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.CI_ACCESS }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
