name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
      - dev

permissions:
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Validate PR
    runs-on: self-hosted

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit tests
        run: |-
          npm install && npm test
